#!/usr/bin/bash

# Activate virtual environment
if [[ "$VIRTUAL_ENV" == "" ]]
then
  source venv/bin/activate
fi

# Run pytest and generate report
python3 -m pytest --html=.reports/pytest/index.html --self-contained-html

# Run coverage and generate report
coverage erase
coverage run -m pytest
coverage html -d .reports/coverage --fail-under 100
